name: Clang-Tidy Analysis

on:
  push:
  pull_request:

jobs:
  clang-tidy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            clang clang-tidy libclang-dev cmake \
            python3-pip

          pip3 install clang-html

      - name: Configure project
        run: |
          export CC=clang
          export CXX=clang++
          ./build.sh

      - name: Run clang-tidy
        run: |
          find src include lib -name '*.cpp' -o -name '*.hpp' | xargs clang-tidy -p . > build/clang-tidy-report.txt || true

      - name: Generate HTML report
        run: |
          clang-tidy-html build/clang-tidy-report.txt -o build/clang-tidy-report.html

      - name: Upload TXT report artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-report
          path: build/clang-tidy-report.txt

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v4
        with:
          name: clang-tidy-report
          path: build/clang-tidy-report.html

      - name: HTML Preview
        id: html_preview
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: build/clang-tidy-report.html
          job_summary: true
